# Generated by Django 2.1.5 on 2019-01-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSite', '0002_useraccounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccounts',
        ),
    ]
