# Generated by Django 2.1.5 on 2019-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSite', '0003_delete_useraccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
